### ISSUE TITLE
10b: Flaeche berechnen und speichern auch wenn keine Points vergeben werden

### ISSUE THREAD

**Issue by dlaumer** [dlaumer/BioDivSchool#11]

**Comment by dlaumer** [comment]
@csailer80: Diesen Fall gibt es glaube ich nur einmal, also dass es im Datenmodell ein Feld fuer die Flaeche gibt obwohl bei dieser Frage keine Punkte vergeben werden. Muss dann die Flaeche wirklich in AGO gespeichert werden? Weil es braeuchte bisschen Aufwand und Code-Refactoring

**Comment by dlaumer** [comment]
@csailer80 bei Kunz nachfragen ob da noch irgendwelche Daten fehlen!

**Comment by csailer80** [comment]
Bei 10b soll in den Resultaten einfach nur die Flächen kommen..

Frage: Kann man bei 10b eine Kategorie "Andere" hinzufügen und das Notizfeld für die Beschreibung des Anderen nutzen?

**Comment by dlaumer** [comment]
Was ist genau mit "Anderen" gemeint?

**Comment by csailer80** [comment]
eine andere Pflanzenart. (Neophyt)

**Comment by dlaumer** [comment]
Ahh verstehe, ja klar kann man machen!

**Comment by dlaumer** [comment]
Ist gemacht
