### ISSUE TITLE
FRAGE: Bei 13 was soll bei ratio geschrieben werden falls keine der Kategorien passt?

### ISSUE THREAD

**Issue by dlaumer** [dlaumer/BioDivSchool#16]

**Comment by csailer80** [comment]
Wir haben die Bewertung falsch verstanden:
Es gibt zur Auswahl ja genau 6 Pflanzenarten resp. Strukturelemente.

![Image](https://user-images.githubusercontent.com/3879340/221188760-69215eb9-be54-4732-a1a5-a516d0378d17.png)



Wir müssen quasi nach der Anzahl DISTINCT Values zählen und entsprechend einordnen

**Comment by dlaumer** [comment]
Gemacht!
