### ISSUE TITLE
FRAGE: Sollte es wirklich zwei Startbildschirme geben?

### ISSUE THREAD

**Issue by dlaumer** [dlaumer/BioDivSchool#18]
Gibt das nicht mehr Wartungsarbeit und Maintenance?

**Comment by csailer80** [comment]
Verstehe Frage nicht..

Ziel:
- BioDivSchool-Viewer: Einsicht in Karte und Projekte: offen für alle anonyme Besucher
- Projekt-Creator: Projekt anlegen und bearbeiten: https://dlaumer.github.io/BioDivSchool/?intern=true (Lehrpersonen)
- Erfassungsapp: Daten erfassen und bearbeiten: https://dlaumer.github.io/BioDivSchool/ (alle)
- Konsolidierungsapp: Daten konsolidieren: https://dlaumer.github.io/BioDivSchool/ (alle)
- Resultateapp: Resultate einsehen und Massnahmen erhalten (PDF Export): https://dlaumer.github.io/BioDivSchool/ (alle)

**Comment by csailer80** [comment]
Analoge Idee: https://www.globe-swiss.ch/de/Angebote/Bioindikation_im_Fliessgewaesser/

![Image](https://user-images.githubusercontent.com/3879340/174580761-4d5cb0fd-8d99-48f7-87d9-c9c5845825d4.png)

WebApp: https://bioindication-maps.globe-swiss.ch/Analyse/

**Comment by dlaumer** [comment]
Nur eine URL, gleicher Startbildschirm fuer alle

**Comment by csailer80** [comment]
Kunz schickt ein Diagramm, um die Komposition der Webapps nochmals zu diskutieren.
