### ISSUE TITLE
White Space

### ISSUE THREAD

**Issue by csailer80** [dlaumer/BioDivSchool#2]
elements need to be verified regarding white space or not

**Comment by dlaumer** [comment]
Ich habe das Problem gelöst indem ich TextInfos welche nur aus Text bestehen **nicht** in so ein solches div getan habe 
`<div class="textInfoElements">`

Das ist eigentlich nur nötig wenn es Bilder drin hat welche nicht zu gross werden sollen und dann nebeinander angeordnet werden sollen
