### ISSUE TITLE
TB220619: Anleitung für das Einzeichnen der Flächen sollte vor den Edit/Add Feature Buttons stehen. Anleitung ergänzen, wie man Flächen bzw. einzelne Punkte löschen kann.

### ISSUE THREAD

**Issue by csailer80** [dlaumer/BioDivSchool#22]

**Comment by dlaumer** [comment]
Anleitung wurde ergänzt. Aber ich müsste mehr Infos haben wie die Anleitung genau vor die Edit/Add Buttons plaziert werden soll. Der Bereich ist recht schmal, das sieht dann doch sehr unschön aus. Auch wird es zu lang sein, dann muss man zu den Edit/Add Buttons scrollen? @csailer80 kannst du das abklären?
