### ISSUE TITLE
Projekt editieren

### ISSUE THREAD

**Issue by csailer80** [dlaumer/BioDivSchool#44]
die Attribute (ProjectID, Name, Schule) bestehende Projekte lassen sich nicht editieren

**Comment by dlaumer** [comment]
Lösung: Fläche schon anklicken beim öffnen

**Comment by dlaumer** [comment]
Temporäre Lösung: Anleing wie man es bearbeiten muss. Evt ist das schon genug?
@csailer80?

**Comment by dlaumer** [comment]
Temporäre Lösung: Anleing wie man es bearbeiten muss. Evt ist das schon genug?
@csailer80?

**Comment by csailer80** [comment]
Müssen Feedback von Kunz haben.. für mich ok.
