### ISSUE TITLE
Nur eigene Projekte editierbar machen

### ISSUE THREAD

**Issue by dlaumer** [dlaumer/BioDivSchool#6]
Falls nicht eingeloggt sollten keine Projekte editierbar sein. Falls schon, dann nur die vom eigenen User.

Ist abgängig von #1

**Comment by dlaumer** [comment]
Dafür müssen die items auf AGOL zuerst nicht mehr public sein.

**Comment by dlaumer** [comment]
@csailer80 Bitte bei der projekt klasse einstellen, dass der creator vom feature registriert wird

**Comment by csailer80** [comment]
Project-DB: username in Attribut owner (Alias: 0_owner) schreiben
