### ISSUE TITLE
Alle Texte im CSV File

### ISSUE THREAD

**Issue by dlaumer** [dlaumer/BioDivSchool#9]
Jeglicher Text welcher in der App am Schluss erscheint muss in die CSV Tabelle (https://github.com/dlaumer/BioDivSchool/blob/main/js/strings/strings.csv) und dann vom Code aus mit dem richtigen Key referenziert werden.

**Comment by csailer80** [comment]
die CSV samt HTML tags ist erstellt. Es fehlen noch die Linktexte <a>

**Comment by dlaumer** [comment]
Finally Done!!
